---

- name: Install generic information-worker software from Apt repositories
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - copyq
    - flameshot
    - gimp
    - lastpass-cli
    - libsox-fmt-mp3
    - mc
    - neovim
    - sox
    - vlc

- name: Install generic information-worker software from Snap package repository
  snap:
    name:
      - emote
      - rocketchat-desktop

- name: Install MS Teams
  ansible.builtin.package:
    state: present
    name: teams

- name: Install fonts
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - fonts-hack-ttf

...
