---

- name: Remove packages
  ansible.builtin.package:
    state: absent
    name: '{{ item }}'
  with_items:
    - command-not-found
    - thunderbird

- name: Install common utils
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - aria2
    - copyq
    - curl
    - flameshot
    - git
    - git-gui
    - htop
    - mc
    - neovim
    - openssh-client
    - tree
    - unzip
    - wget
    - xterm

...
