---

- name: Remove packages
  ansible.builtin.package:
    state: absent
    name: '{{ item }}'
  with_items:
    - command-not-found
    - thunderbird

- name: Install common utils
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - copyq
    - flameshot
    - git
    - htop
    - mc
    - neovim
    - tree

...
