---

- name: Install development tools
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - ansible
    - ansible-lint
    - gawk
    - jq
    - python3-pip
    - python3-venv
    - ripgrep
    - tig
    - zeal

- name: Import Clang task
  ansible.builtin.import_tasks: clang.yaml

...
