---

- name: Install development tools
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - ansible
    - ansible-lint
    - apt-file
    - docker.io
    - gawk
    - jq
    - openssh-server
    - python3-pip
    - python3-venv
    - repo
    - ripgrep
    - rsync
    - sysstat
    - tig
    - tree
    - zeal
    - zsh
    - zstd


- name: Import Clang task
  ansible.builtin.import_tasks: clang.yaml


- name: Install VS Code
  ansible.builtin.package:
    state: present
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"


- name: Install MS Teams
  ansible.builtin.package:
    state: present
    name: teams

...
