---

- name: Add VS Code repo
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] {{ microsoft_packages_server }}/repos/vscode stable main'
    filename: vscode
    state: present

- name: Install VS Code
  become: yes
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present

...
