---

- name: Install generic information-worker software
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - copyq
    - flameshot
    - lastpass-cli
    - mc
    - neovim

...
