---

- ansible.builtin.apt_key:
    url: '{{ microsoft_packages_server }}/keys/microsoft.asc'
    keyring: microsoft
    state: present
  become: yes

- ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] {{ microsoft_packages_server }}/repos/ms-teams stable main'
    filename: microsoft
    state: present
  become: yes

- ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] {{ microsoft_packages_server }}/repos/vscode stable main'
    filename: microsoft
    state: present
  become: yes

# TODO: chmod o+r /etc/apt/sources.list.d/teams.list
# TODO: chmod o+r /etc/apt/sources.list.d/vscode.list

...
