---

- name: Import information_worker play
  import_playbook: information_worker.yaml

- name: Import python play
  import_playbook: python.yaml

- hosts: all
  roles:
    - devpc
    - yocto
    - diodonfrost.terraform
    - diodonfrost.terragrunt
    - Comcast.sdkman

...
