---

- name: Check for AWS CLI installation
  stat:
    path: /usr/local/bin/aws
  register: aws

- name: Download AWS CLI v2 installer
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: "{{ executable_temp_dir | default('/tmp') }}"
    remote_src: yes
    creates: /tmp/aws
    mode: 0755
  when: not aws.stat.exists

- name: Run the AWS CLI v2 installer
  command:
  args:
    cmd: "{{ executable_temp_dir | default('/tmp') }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install
  when: not aws.stat.exists

- name: Make AWS CLI package discoverable
  ansible.builtin.file:
    path: /usr/local/aws-cli
    mode: o=rx
    follow: no
    state: directory
    recurse: yes

- name: Show installer output
  debug:
    var: aws_install
    verbosity: 2

# Install a snap with classic confinement
- name: Install amazon-ssm-agent
  community.general.snap:
    name: amazon-ssm-agent
    classic: yes

# TODO  curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
# TODO  sudo dpkg --install session-manager-plugin.deb

...
