---

- name: Install development tools
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - ansible
    - ansible-lint
    - apt-file
    - build-essential
    - ccache
    - chrpath
    - cloc
    - cpio
    - debianutils
    - diffstat
    - docker.io
    - fzf
    - gawk
    - git-crypt
    - jq
    - meld
    - ninja-build
    - openssh-server
    - repo
    - ripgrep
    - rsync
    - socat
    - sshpass
    - stow
    - subversion
    - sysstat
    - tig
    - tree
    - xz-utils
    - zeal
    - zsh
    - zstd


- name: VS Code
  ansible.builtin.package:
    state: present
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"


- name: IntelliJ IDEA
  community.general.snap:
    state: present
    name: intellij-idea-community
    classic: yes


- name: AWS stack
  ansible.builtin.import_tasks: aws.yaml


- name: Clang/LLVM stack
  ansible.builtin.import_tasks: clang.yaml


- name: Kubernetes stack
  ansible.builtin.import_tasks: k8.yaml


- name: JFrog utils
  ansible.builtin.import_tasks: jfrog.yaml


- name: Zsh stack
  ansible.builtin.import_tasks: zsh.yaml

...
