---

- name: Install development tools
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - ansible
    - ansible-lint
    - apt-file
    - build-essential
    - chrpath
    - cloc
    - cpio
    - debianutils
    - diffstat
    - docker.io
    - gawk
    - jq
    - meld
    - ninja-build
    - openssh-server
    - python3-git
    - python3-jinja2
    - python3-pip
    - python3-venv
    - repo
    - ripgrep
    - rsync
    - socat
    - sysstat
    - tig
    - tree
    - xz-utils
    - zeal
    - zsh
    - zstd


- name: Import Clang task
  ansible.builtin.import_tasks: clang.yaml


- name: Install VS Code
  ansible.builtin.package:
    state: present
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"


- name: Install MS Teams
  ansible.builtin.package:
    state: present
    name: teams


- name: Import AWS task
  ansible.builtin.import_tasks: aws.yaml

...
