---

- name: Install development tools
  ansible.builtin.package:
    state: present
    name: '{{ item }}'
  with_items:
    - ansible
    - ansible-lint
    - apt-file
    - build-essential
    - chrpath
    - cloc
    - cpio
    - debianutils
    - diffstat
    - docker.io
    - gawk
    - git-crypt
    - jq
    - meld
    - ninja-build
    - openssh-server
    - repo
    - ripgrep
    - rsync
    - socat
    - sysstat
    - tig
    - tree
    - xz-utils
    - zeal
    - zsh
    - zstd


- name: Install VS Code
  ansible.builtin.package:
    state: present
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"


- name: Install MS Teams
  ansible.builtin.package:
    state: present
    name: teams


- name: AWS stack
  ansible.builtin.import_tasks: aws.yaml


- name: Clang/LLVM stack
  ansible.builtin.import_tasks: clang.yaml


- name: Kubernetes stack
  ansible.builtin.import_tasks: k8.yaml


- name: Node stack
  ansible.builtin.import_tasks: node.yaml


- name: Python stack
  ansible.builtin.import_tasks: python.yaml

...
